accounts-ui:
  podAnnotations:
    secret.reloader.stakater.com/reload: ace-config
global:
  infra:
    avatars:
      bucket: gs://ace/avatars
    badger:
      levels: 0
      mountPath: ""
    dns:
      auth:
        email: '---'
        token: XYZ
      provider: cloudflare
    invoice:
      bucket: ""
      mountPath: ""
      trackerEmail: ""
    kms:
      masterKeyURL: base64key://jnhw8v2dVqBmc2xEaIjXfG7ekdsEfdfsfremZpWeY7bWEWKI0nDBPzk8ceTDxo8Z
    objstore:
      auth:
        serviceAccountJson: '{"secret": "json"}'
    tls:
      email: ops@appscode.cloud
  monitoring:
    agent: prometheus.io/operator
    exporter:
      resources:
        limits:
          memory: 128Mi
    serviceMonitor:
      labels:
        release: kube-prometheus-stack
  platform:
    domain: appscode.cloud
grafana:
  podAnnotations:
    secret.reloader.stakater.com/reload: ace-config
ingress-dns:
  domainFilters:
  - appscode.cloud
  enabled: true
  env:
  - name: CF_API_TOKEN
    value: XYZ
  extraArgs:
  - --ignore-ingress-tls-spec
  image:
    pullPolicy: IfNotPresent
    repository: appscode/external-dns
    tag: external-dns-helm-chart-1.9.0-1-gbd1bb40c
  logLevel: debug
  policy: sync
  provider: cloudflare
  registry: txt
  sources:
  - ingress
  txtOwnerId: ingress-dns
ingress-nginx:
  controller:
    hostPort:
      enabled: true
    ingressClassByName: true
    ingressClassResource:
      controllerValue: k8s.io/ingress-nginx-ace
      enabled: true
      name: nginx-ace
    kind: DaemonSet
    service:
      external:
        enabled: false
nats:
  auth:
    enabled: true
    operatorjwt:
      configMap:
        key: Operator.jwt
        name: ace-nats-cred
    resolver:
      operator: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJhdWQiOiJPQkxKVjZKWUNZSUVHUVBPVUpXVzNNV0lONEQ2UFoyM0VRNlBMVU5VU1JYQ1pKNk02NldBUlBONyIsImV4cCI6NDgxMjIxOTU0NSwianRpIjoiRVBLUlc1UEpLWUxJNzNQUllXNDM0Q0VURVBJTVZMSFZJSUdZRjJQSE9FRkJZRUpUMzZGUSIsImlhdCI6MTY1NjU0NTk0NSwiaXNzIjoiT0JMSlY2SllDWUlFR1FQT1VKV1czTVdJTjRENlBaMjNFUTZQTFVOVVNSWENaSjZNNjZXQVJQTjciLCJuYW1lIjoiT3BlcmF0b3IiLCJuYmYiOjE2NTY1NDU5NDUsInN1YiI6Ik9CTEpWNkpZQ1lJRUdRUE9VSldXM01XSU40RDZQWjIzRVE2UExVTlVTUlhDWko2TTY2V0FSUE43IiwibmF0cyI6eyJzaWduaW5nX2tleXMiOlsiT0JMSlY2SllDWUlFR1FQT1VKV1czTVdJTjRENlBaMjNFUTZQTFVOVVNSWENaSjZNNjZXQVJQTjciXSwidHlwZSI6Im9wZXJhdG9yIiwidmVyc2lvbiI6Mn19.yBrmvuQE-bmXaKeDDIlqW3mZ4oKhe6IQ_3rxZaPX-NJjPbYAR-gjezTbUSyCcz1j2Dou32QB-wuQtB_dDwsMAw
      resolverPreload:
        AASQZ5OTQJIKWEEZWCMGZHDIGB264JGKV22HRLOZGEU26WVDICTM4XEG: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiIzRkdUR0haUkkyNjNSNTVRNVczQVRQV1dBQVJXNTM3NUtLNDNTNkRKRE0zUzZWTUNGWDJBIiwiaWF0IjoxNjU2NTQ1OTQ1LCJpc3MiOiJPQkxKVjZKWUNZSUVHUVBPVUpXVzNNV0lONEQ2UFoyM0VRNlBMVU5VU1JYQ1pKNk02NldBUlBONyIsIm5hbWUiOiJBZG1pbiIsInN1YiI6IkFBU1FaNU9UUUpJS1dFRVpXQ01HWkhESUdCMjY0SkdLVjIySFJMT1pHRVUyNldWRElDVE00WEVHIiwibmF0cyI6eyJsaW1pdHMiOnsic3VicyI6LTEsImRhdGEiOi0xLCJwYXlsb2FkIjotMSwiaW1wb3J0cyI6LTEsImV4cG9ydHMiOi0xLCJ3aWxkY2FyZHMiOnRydWUsImNvbm4iOi0xLCJsZWFmIjotMSwibWVtX3N0b3JhZ2UiOi0xLCJkaXNrX3N0b3JhZ2UiOi0xLCJzdHJlYW1zIjotMSwiY29uc3VtZXIiOi0xfSwiZGVmYXVsdF9wZXJtaXNzaW9ucyI6eyJwdWIiOnt9LCJzdWIiOnt9fSwidHlwZSI6ImFjY291bnQiLCJ2ZXJzaW9uIjoyfX0.p2BJZKLK3u349Ynq6prMnKT4fj4wxBLTQ7ig5hhgwOoU78AJA4S-pYKlYGq1cG6hSFoQb2VdWFcAcR6B-Ph5Bw
        ABL5KPR6KLN3SUVHDCCCOFVVNIUINAZLALXXUL7CSBJPQPKYL2SWV3EL: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiIzVkJBUjRNWUJMNlBPT1VCS1RLS0gyT1BHU1hYT01XRUo3TTNDU1dSWVA0SVBHWlFWSFRRIiwiaWF0IjoxNjU2NTQ1OTQ1LCJpc3MiOiJPQkxKVjZKWUNZSUVHUVBPVUpXVzNNV0lONEQ2UFoyM0VRNlBMVU5VU1JYQ1pKNk02NldBUlBONyIsIm5hbWUiOiJTWVMiLCJzdWIiOiJBQkw1S1BSNktMTjNTVVZIRENDQ09GVlZOSVVJTkFaTEFMWFhVTDdDU0JKUFFQS1lMMlNXVjNFTCIsIm5hdHMiOnsibGltaXRzIjp7InN1YnMiOi0xLCJkYXRhIjotMSwicGF5bG9hZCI6LTEsImltcG9ydHMiOi0xLCJleHBvcnRzIjotMSwid2lsZGNhcmRzIjp0cnVlLCJjb25uIjotMSwibGVhZiI6LTF9LCJkZWZhdWx0X3Blcm1pc3Npb25zIjp7InB1YiI6e30sInN1YiI6e319LCJ0eXBlIjoiYWNjb3VudCIsInZlcnNpb24iOjJ9fQ.B7n5T2ssb9PtZQdiNlHP4o88tUHW3Oa8awJ3jLbJDM0bQtFYHzfSXJ8NN830HP8aOMLwhcIPS96x-zx4lzclDw
      store:
        dir: /etc/nats-config/accounts/jwt
        size: 10Gi
        storageClassName: standard
      systemAccount: ABL5KPR6KLN3SUVHDCCCOFVVNIUINAZLALXXUL7CSBJPQPKYL2SWV3EL
      type: full
    systemAccount: ABL5KPR6KLN3SUVHDCCCOFVVNIUINAZLALXXUL7CSBJPQPKYL2SWV3EL
  exporter:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
      path: /metrics
  nats:
    externalAccess: true
    jetstream:
      enabled: true
      fileStorage:
        enabled: true
        size: 10Gi
        storageClassName: standard
        storageDirectory: /nats/jetstream
    limits:
      maxPayload: 4Mb
    logging:
      debug: false
      trace: false
    resources:
      limits:
        memory: 2Gi
      requests:
        memory: 2Gi
    tls:
      allow_non_tls: false
      ca: ""
      cert: tls.crt
      key: tls.key
      secret:
        name: ace-cert
  statefulSetPodLabels:
    secret.reloader.stakater.com/reload: ace-cert
  websocket:
    allowedOrigins:
    - https://appscode.cloud
    - https://console.appscode.cloud
    - https://kubedb.appscode.cloud
    - https://grafana.appscode.cloud
    enabled: true
    port: 443
    tls:
      ca: ""
      cert: tls.crt
      key: tls.key
      secret:
        name: ace-cert
nats-dns:
  domainFilters:
  - appscode.cloud
  enabled: true
  env:
  - name: CF_API_TOKEN
    value: XYZ
  extraArgs:
  - --fqdn-template=nats.appscode.cloud
  - --label-filter=
  image:
    pullPolicy: IfNotPresent
    repository: appscode/external-dns
    tag: external-dns-helm-chart-1.9.0-1-gbd1bb40c
  logLevel: debug
  policy: sync
  provider: cloudflare
  registry: txt
  sources:
  - node
  txtOwnerId: nats-dns
platform-api:
  podAnnotations:
    secret.reloader.stakater.com/reload: ace-config
platform-ui:
  podAnnotations:
    secret.reloader.stakater.com/reload: ace-config
prom-proxy:
  podAnnotations:
    secret.reloader.stakater.com/reload: ace-config
settings:
  cache:
    auth:
      password: zO3kEwZjzhh8MqZI
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 512Mi
  db:
    auth:
      password: mOcM$Eh)K4H$U&kX
    databaseName: ace
    persistence:
      size: 20Gi
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 512Mi
  nats:
    adminCreds: |
      -----BEGIN NATS ACCOUNT JWT-----
      eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiIzRkdUR0haUkkyNjNSNTVRNVczQVRQV1dBQVJXNTM3NUtLNDNTNkRKRE0zUzZWTUNGWDJBIiwiaWF0IjoxNjU2NTQ1OTQ1LCJpc3MiOiJPQkxKVjZKWUNZSUVHUVBPVUpXVzNNV0lONEQ2UFoyM0VRNlBMVU5VU1JYQ1pKNk02NldBUlBONyIsIm5hbWUiOiJBZG1pbiIsInN1YiI6IkFBU1FaNU9UUUpJS1dFRVpXQ01HWkhESUdCMjY0SkdLVjIySFJMT1pHRVUyNldWRElDVE00WEVHIiwibmF0cyI6eyJsaW1pdHMiOnsic3VicyI6LTEsImRhdGEiOi0xLCJwYXlsb2FkIjotMSwiaW1wb3J0cyI6LTEsImV4cG9ydHMiOi0xLCJ3aWxkY2FyZHMiOnRydWUsImNvbm4iOi0xLCJsZWFmIjotMSwibWVtX3N0b3JhZ2UiOi0xLCJkaXNrX3N0b3JhZ2UiOi0xLCJzdHJlYW1zIjotMSwiY29uc3VtZXIiOi0xfSwiZGVmYXVsdF9wZXJtaXNzaW9ucyI6eyJwdWIiOnt9LCJzdWIiOnt9fSwidHlwZSI6ImFjY291bnQiLCJ2ZXJzaW9uIjoyfX0.p2BJZKLK3u349Ynq6prMnKT4fj4wxBLTQ7ig5hhgwOoU78AJA4S-pYKlYGq1cG6hSFoQb2VdWFcAcR6B-Ph5Bw
      ------END NATS ACCOUNT JWT------

      ************************* IMPORTANT *************************
      NKEY Seed printed below can be used to sign and prove identity.
      NKEYs are sensitive and should be treated as secrets.

      -----BEGIN ACCOUNT NKEY SEED-----
      SAAM6LA3PWN33R54YYO4ZVNNBJQEJRSYSC6DRZBOZXAUYFJVYS2UNFTL5I
      ------END ACCOUNT NKEY SEED------

      *************************************************************
    adminUserCreds: |
      -----BEGIN NATS USER JWT-----
      eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJHUllPRE1OVVlGWkUzNUNGQlRMQ0hPRFBHTlpGTjVHQ0hZWlNXTUlMT0VLMk9UQjNQQzVBIiwiaWF0IjoxNjU2NTQ1OTQ1LCJpc3MiOiJBQVNRWjVPVFFKSUtXRUVaV0NNR1pIRElHQjI2NEpHS1YyMkhSTE9aR0VVMjZXVkRJQ1RNNFhFRyIsIm5hbWUiOiJhZG1pbiIsInN1YiI6IlVBVVhPRzdRSjVNUUNYWkpIUENESFFYU1NENTRIQkNERkNaUUxZQ1hITFdQRVQ3TVhBQkFJVVJXIiwibmF0cyI6eyJwdWIiOnt9LCJzdWIiOnt9LCJzdWJzIjotMSwiZGF0YSI6LTEsInBheWxvYWQiOi0xLCJ0eXBlIjoidXNlciIsInZlcnNpb24iOjJ9fQ.v_EtQ0w7mD7sA9k8VYGDW20eqQttqhggFJSJsgTyifTorxStkLHNFNga9LZ_nAnLt-WZ_oGl7kT-49-f_EPQAQ
      ------END NATS USER JWT------

      ************************* IMPORTANT *************************
      NKEY Seed printed below can be used to sign and prove identity.
      NKEYs are sensitive and should be treated as secrets.

      -----BEGIN USER NKEY SEED-----
      SUAPTJHFKHGERN2RRUMATMLOP62T2W3DUJ6D32NPPTK2WIKYTBZV57WEXM
      ------END USER NKEY SEED------

      *************************************************************
    operatorCreds: |
      -----BEGIN NATS OPERATOR JWT-----
      eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJhdWQiOiJPQkxKVjZKWUNZSUVHUVBPVUpXVzNNV0lONEQ2UFoyM0VRNlBMVU5VU1JYQ1pKNk02NldBUlBONyIsImV4cCI6NDgxMjIxOTU0NSwianRpIjoiRVBLUlc1UEpLWUxJNzNQUllXNDM0Q0VURVBJTVZMSFZJSUdZRjJQSE9FRkJZRUpUMzZGUSIsImlhdCI6MTY1NjU0NTk0NSwiaXNzIjoiT0JMSlY2SllDWUlFR1FQT1VKV1czTVdJTjRENlBaMjNFUTZQTFVOVVNSWENaSjZNNjZXQVJQTjciLCJuYW1lIjoiT3BlcmF0b3IiLCJuYmYiOjE2NTY1NDU5NDUsInN1YiI6Ik9CTEpWNkpZQ1lJRUdRUE9VSldXM01XSU40RDZQWjIzRVE2UExVTlVTUlhDWko2TTY2V0FSUE43IiwibmF0cyI6eyJzaWduaW5nX2tleXMiOlsiT0JMSlY2SllDWUlFR1FQT1VKV1czTVdJTjRENlBaMjNFUTZQTFVOVVNSWENaSjZNNjZXQVJQTjciXSwidHlwZSI6Im9wZXJhdG9yIiwidmVyc2lvbiI6Mn19.yBrmvuQE-bmXaKeDDIlqW3mZ4oKhe6IQ_3rxZaPX-NJjPbYAR-gjezTbUSyCcz1j2Dou32QB-wuQtB_dDwsMAw
      ------END NATS OPERATOR JWT------

      ************************* IMPORTANT *************************
      NKEY Seed printed below can be used to sign and prove identity.
      NKEYs are sensitive and should be treated as secrets.

      -----BEGIN OPERATOR NKEY SEED-----
      SOADQSWOLQFUTXYXI3CFDHLZMDSZAHJTMVA2WWVUILK7S7MGO2UPET6M74
      ------END OPERATOR NKEY SEED------

      *************************************************************
    operatorJwt: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJhdWQiOiJPQkxKVjZKWUNZSUVHUVBPVUpXVzNNV0lONEQ2UFoyM0VRNlBMVU5VU1JYQ1pKNk02NldBUlBONyIsImV4cCI6NDgxMjIxOTU0NSwianRpIjoiRVBLUlc1UEpLWUxJNzNQUllXNDM0Q0VURVBJTVZMSFZJSUdZRjJQSE9FRkJZRUpUMzZGUSIsImlhdCI6MTY1NjU0NTk0NSwiaXNzIjoiT0JMSlY2SllDWUlFR1FQT1VKV1czTVdJTjRENlBaMjNFUTZQTFVOVVNSWENaSjZNNjZXQVJQTjciLCJuYW1lIjoiT3BlcmF0b3IiLCJuYmYiOjE2NTY1NDU5NDUsInN1YiI6Ik9CTEpWNkpZQ1lJRUdRUE9VSldXM01XSU40RDZQWjIzRVE2UExVTlVTUlhDWko2TTY2V0FSUE43IiwibmF0cyI6eyJzaWduaW5nX2tleXMiOlsiT0JMSlY2SllDWUlFR1FQT1VKV1czTVdJTjRENlBaMjNFUTZQTFVOVVNSWENaSjZNNjZXQVJQTjciXSwidHlwZSI6Im9wZXJhdG9yIiwidmVyc2lvbiI6Mn19.yBrmvuQE-bmXaKeDDIlqW3mZ4oKhe6IQ_3rxZaPX-NJjPbYAR-gjezTbUSyCcz1j2Dou32QB-wuQtB_dDwsMAw
    systemCreds: |
      -----BEGIN NATS ACCOUNT JWT-----
      eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiIzVkJBUjRNWUJMNlBPT1VCS1RLS0gyT1BHU1hYT01XRUo3TTNDU1dSWVA0SVBHWlFWSFRRIiwiaWF0IjoxNjU2NTQ1OTQ1LCJpc3MiOiJPQkxKVjZKWUNZSUVHUVBPVUpXVzNNV0lONEQ2UFoyM0VRNlBMVU5VU1JYQ1pKNk02NldBUlBONyIsIm5hbWUiOiJTWVMiLCJzdWIiOiJBQkw1S1BSNktMTjNTVVZIRENDQ09GVlZOSVVJTkFaTEFMWFhVTDdDU0JKUFFQS1lMMlNXVjNFTCIsIm5hdHMiOnsibGltaXRzIjp7InN1YnMiOi0xLCJkYXRhIjotMSwicGF5bG9hZCI6LTEsImltcG9ydHMiOi0xLCJleHBvcnRzIjotMSwid2lsZGNhcmRzIjp0cnVlLCJjb25uIjotMSwibGVhZiI6LTF9LCJkZWZhdWx0X3Blcm1pc3Npb25zIjp7InB1YiI6e30sInN1YiI6e319LCJ0eXBlIjoiYWNjb3VudCIsInZlcnNpb24iOjJ9fQ.B7n5T2ssb9PtZQdiNlHP4o88tUHW3Oa8awJ3jLbJDM0bQtFYHzfSXJ8NN830HP8aOMLwhcIPS96x-zx4lzclDw
      ------END NATS ACCOUNT JWT------

      ************************* IMPORTANT *************************
      NKEY Seed printed below can be used to sign and prove identity.
      NKEYs are sensitive and should be treated as secrets.

      -----BEGIN ACCOUNT NKEY SEED-----
      SAAOB5PLIK7PYUSGMDG5KGCCGNGLXACI6TF3XY3ZPQR3YJP36QN4FWHXUE
      ------END ACCOUNT NKEY SEED------

      *************************************************************
    systemJwt: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiIzVkJBUjRNWUJMNlBPT1VCS1RLS0gyT1BHU1hYT01XRUo3TTNDU1dSWVA0SVBHWlFWSFRRIiwiaWF0IjoxNjU2NTQ1OTQ1LCJpc3MiOiJPQkxKVjZKWUNZSUVHUVBPVUpXVzNNV0lONEQ2UFoyM0VRNlBMVU5VU1JYQ1pKNk02NldBUlBONyIsIm5hbWUiOiJTWVMiLCJzdWIiOiJBQkw1S1BSNktMTjNTVVZIRENDQ09GVlZOSVVJTkFaTEFMWFhVTDdDU0JKUFFQS1lMMlNXVjNFTCIsIm5hdHMiOnsibGltaXRzIjp7InN1YnMiOi0xLCJkYXRhIjotMSwicGF5bG9hZCI6LTEsImltcG9ydHMiOi0xLCJleHBvcnRzIjotMSwid2lsZGNhcmRzIjp0cnVlLCJjb25uIjotMSwibGVhZiI6LTF9LCJkZWZhdWx0X3Blcm1pc3Npb25zIjp7InB1YiI6e30sInN1YiI6e319LCJ0eXBlIjoiYWNjb3VudCIsInZlcnNpb24iOjJ9fQ.B7n5T2ssb9PtZQdiNlHP4o88tUHW3Oa8awJ3jLbJDM0bQtFYHzfSXJ8NN830HP8aOMLwhcIPS96x-zx4lzclDw
    systemPubKey: ABL5KPR6KLN3SUVHDCCCOFVVNIUINAZLALXXUL7CSBJPQPKYL2SWV3EL
    systemUserCreds: |
      -----BEGIN NATS USER JWT-----
      eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJDRTJNWFUzS1ZJRUQyRVhaWElUTjYzU1NPS1VaMzVOV09LWUtKVFNGTTVHMjZSQ0RIQlFBIiwiaWF0IjoxNjU2NTQ1OTQ1LCJpc3MiOiJBQkw1S1BSNktMTjNTVVZIRENDQ09GVlZOSVVJTkFaTEFMWFhVTDdDU0JKUFFQS1lMMlNXVjNFTCIsIm5hbWUiOiJzeXMiLCJzdWIiOiJVQkFGUDZNUDVNUllITkI2TVk3TEVXQllDU0JHNURGQTJNQ0taUzJTSUVHTk1CWDI3Tkk3N1VJVSIsIm5hdHMiOnsicHViIjp7fSwic3ViIjp7fSwic3VicyI6LTEsImRhdGEiOi0xLCJwYXlsb2FkIjotMSwidHlwZSI6InVzZXIiLCJ2ZXJzaW9uIjoyfX0.JiuIFI1pn0AosGpPDxR3fIzTa298_UPr1ljXsfweheyqLAu5XR9V79luXyoJ7Ti2US66RQF1a7AycNJ3W2i4DA
      ------END NATS USER JWT------

      ************************* IMPORTANT *************************
      NKEY Seed printed below can be used to sign and prove identity.
      NKEYs are sensitive and should be treated as secrets.

      -----BEGIN USER NKEY SEED-----
      SUAJVUKBWYJJJGAQF255UKULHZIKZAXKRNCZONMHK2UCHGI2Y4YFCR2AGY
      ------END USER NKEY SEED------

      *************************************************************
  platform:
    serviceRegisterEmailConfirm: false
  searchlight:
    alertmanagerAddr: ""
    enabled: false
    m3coordinatorAddr: ""
    queryAddr: ""
    rulerAddr: ""
  security:
    csrfSecretKey: aRILruwtlRzy93moe1FJInbErozGj7p20HUwCGhKbUy2RNqlvrZDJpUZQdZA17jB
    oauth2JWTSecret: sHuX46j0oSFv4yoPwNlaLpKduXoyW2x88ZxIe1dVO4k
  smtp:
    from: ""
    host: ""
    password: ""
    subjectPrefix: ACE |
    username: ""
  stripe:
    endpointSecret: ""
    stripeKey: ""
