{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hello.serviceAccountName" . }}
  labels:
    {{- include "hello.labels" . | nindent 4 }}
  annotations:
    values: |
    {{- toYaml .Values | nindent 6 }}
{{- end }}
